# this config was migrated from renv.lock on 2026-10-09
[project]
name = "idash"
r_version = "4.6.1"

repositories = [
    { alias = "CRAN", url = "https://cran.rstudio.com/"}
]

dependencies = [
    { name = "DBI", repository = "CRAN" },
    { name = "DT", repository = "CRAN" },
    { name = "MatrixModels", repository = "CRAN" },
    { name = "R6", repository = "CRAN" },
    { name = "RColorBrewer", repository = "CRAN" },
    { name = "Rcpp", repository = "CRAN" },
    { name = "S7", repository = "CRAN" },
    { name = "SparseM", repository = "CRAN" },
    { name = "askpass", repository = "CRAN" },
    { name = "backports", repository = "CRAN" },
    { name = "base64enc", repository = "CRAN" },
    { name = "bit", repository = "CRAN" },
    { name = "bit64", repository = "CRAN" },
    { name = "blob", repository = "CRAN" },
    { name = "broom", repository = "CRAN" },
    { name = "bslib", repository = "CRAN" },
    { name = "cachem", repository = "CRAN" },
    { name = "callr", repository = "CRAN" },
    { name = "cellranger", repository = "CRAN" },
    { name = "cli", repository = "CRAN" },
    { name = "clipr", repository = "CRAN" },
    { name = "commonmark", repository = "CRAN" },
    { name = "conflicted", repository = "CRAN" },
    { name = "cpp11", repository = "CRAN" },
    { name = "crayon", repository = "CRAN" },
    { name = "crosstalk", repository = "CRAN" },
    { name = "dbplyr", repository = "CRAN" },
    { name = "digest", repository = "CRAN" },
    { name = "doFuture", repository = "CRAN" },
    { name = "dplyr", repository = "CRAN" },
    { name = "dtplyr", repository = "CRAN" },
    { name = "evaluate", repository = "CRAN" },
    { name = "exuber", repository = "CRAN" },
    { name = "farver", repository = "CRAN" },
    { name = "fastmap", repository = "CRAN" },
    { name = "fontawesome", repository = "CRAN" },
    { name = "forcats", repository = "CRAN" },
    { name = "foreach", repository = "CRAN" },
    { name = "fresh", repository = "CRAN" },
    { name = "fs", repository = "CRAN" },
    { name = "future.apply", repository = "CRAN" },
    { name = "gargle", repository = "CRAN" },
    { name = "generics", repository = "CRAN" },
    { name = "ggplot2", repository = "CRAN" },
    { name = "globals", repository = "CRAN" },
    { name = "glue", repository = "CRAN" },
    { name = "googledrive", repository = "CRAN" },
    { name = "googlesheets4", repository = "CRAN" },
    { name = "gtable", repository = "CRAN" },
    { name = "haven", repository = "CRAN" },
    { name = "here", repository = "CRAN" },
    { name = "highr", repository = "CRAN" },
    { name = "hms", repository = "CRAN" },
    { name = "htmltools", repository = "CRAN" },
    { name = "htmlwidgets", repository = "CRAN" },
    { name = "httpuv", repository = "CRAN" },
    { name = "ids", repository = "CRAN" },
    { name = "isoband", repository = "CRAN" },
    { name = "iterators", repository = "CRAN" },
    { name = "jquerylib", repository = "CRAN" },
    { name = "jsonlite", repository = "CRAN" },
    { name = "labeling", repository = "CRAN" },
    { name = "later", repository = "CRAN" },
    { name = "lazyeval", repository = "CRAN" },
    { name = "lifecycle", repository = "CRAN" },
    { name = "listenv", repository = "CRAN" },
    { name = "lubridate", repository = "CRAN" },
    { name = "magrittr", repository = "CRAN" },
    { name = "memoise", repository = "CRAN" },
    { name = "mime", repository = "CRAN" },
    { name = "modelr", repository = "CRAN" },
    { name = "openssl", repository = "CRAN" },
    { name = "otel", repository = "CRAN" },
    { name = "parallelly", repository = "CRAN" },
    { name = "patchwork", repository = "CRAN" },
    { name = "pillar", repository = "CRAN" },
    { name = "pkgconfig", repository = "CRAN" },
    { name = "prettyunits", repository = "CRAN" },
    { name = "processx", repository = "CRAN" },
    { name = "progress", repository = "CRAN" },
    { name = "progressr", repository = "CRAN" },
    { name = "promises", repository = "CRAN" },
    { name = "ps", repository = "CRAN" },
    { name = "purrr", repository = "CRAN" },
    { name = "quantreg", repository = "CRAN" },
    { name = "ragg", repository = "CRAN" },
    { name = "rappdirs", repository = "CRAN" },
    { name = "readr", repository = "CRAN" },
    { name = "rematch", repository = "CRAN" },
    { name = "rematch2", repository = "CRAN" },
    { name = "renv", repository = "CRAN" },
    { name = "reprex", repository = "CRAN" },
    { name = "rlang", repository = "CRAN" },
    { name = "rprojroot", repository = "CRAN" },
    { name = "rstudioapi", repository = "CRAN" },
    { name = "rvest", repository = "CRAN" },
    { name = "sass", repository = "CRAN" },
    { name = "scales", repository = "CRAN" },
    { name = "shiny", repository = "CRAN" },
    { name = "shinyWidgets", repository = "CRAN" },
    { name = "shinydashboard", repository = "CRAN" },
    { name = "shinydashboardPlus", repository = "CRAN" },
    { name = "sourcetools", repository = "CRAN" },
    { name = "stringi", repository = "CRAN" },
    { name = "stringr", repository = "CRAN" },
    { name = "sys", repository = "CRAN" },
    { name = "systemfonts", repository = "CRAN" },
    { name = "textshaping", repository = "CRAN" },
    { name = "tibble", repository = "CRAN" },
    { name = "tidyr", repository = "CRAN" },
    { name = "tidyselect", repository = "CRAN" },
    { name = "tidyverse", repository = "CRAN" },
    { name = "timechange", repository = "CRAN" },
    { name = "transx", repository = "CRAN" },
    { name = "tzdb", repository = "CRAN" },
    { name = "utf8", repository = "CRAN" },
    { name = "uuid", repository = "CRAN" },
    { name = "vctrs", repository = "CRAN" },
    { name = "viridisLite", repository = "CRAN" },
    { name = "vroom", repository = "CRAN" },
    { name = "waiter", repository = "CRAN" },
    { name = "withr", repository = "CRAN" },
    { name = "xml2", repository = "CRAN" },
    { name = "xtable", repository = "CRAN" },
    { name = "yaml", repository = "CRAN" },
    { name = "ivx", git = "https://github.com/kvasilopoulos/ivx", branch = "master" },
    "readxl",
    "zoo",
    "rmarkdown",
]
